# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: 'PCMR-pool'  # Reemplaza con el nombre del pool que creaste
  demands:
  - agent.name -equals 'PCMR-agent'

steps:
- script: echo "Running on Self-Hosted Agent"
  displayName: 'Check Agent'

- task: Maven@3
  displayName: 'Run API Tests'
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'test'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

- task: PublishTestResults@2
  displayName: 'Publish JUnit Test Results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mergeTestResults: true
    testRunTitle: 'API Test Results'

